# -*- coding: utf-8 -*-
from __future__ import annotations

# Latest controlled equipment master data transcribed from the seven-page
# DLBP-CX-P05-R10 ledger supplied in July 2026.
# Blank cells remain blank. Row 3's name is retained as 百分表 from the
# previously confirmed ledger because the latest photo leaves that cell blank.

EQUIPMENT_CATALOG = [{'seq': 1,
  'name': '数显游标卡尺',
  'model': '',
  'range': '（0～150）mm',
  'manufacturer': '',
  'serial_no': '',
  'management_no': 'BPGL-A001',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 2,
  'name': '千分尺',
  'model': '',
  'range': '',
  'manufacturer': '',
  'serial_no': '',
  'management_no': 'BPGL-A002',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 3,
  'name': '百分表',
  'model': '',
  'range': '',
  'manufacturer': '',
  'serial_no': '',
  'management_no': 'BPGL-A003',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 4,
  'name': '螺纹千分尺',
  'model': '',
  'range': '（0～25）mm',
  'manufacturer': '',
  'serial_no': '230308408',
  'management_no': 'BPGL-A004',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 5,
  'name': '测厚仪',
  'model': '/',
  'range': '（0～10）mm/0.1 mm',
  'manufacturer': '上海九量五金工具有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A005',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 6,
  'name': '电子秒表',
  'model': 'YS-801',
  'range': '0.01 s～99 h 59 min 59.99 s；分辨力：0.01 s',
  'manufacturer': '深圳市弈圣科技有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A006',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 7,
  'name': '电子秒表',
  'model': 'YS-801',
  'range': '0.01 s～99 h 59 min 59.99 s；分辨力：0.01 s',
  'manufacturer': '深圳市弈圣科技有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A007',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 8,
  'name': '电子秒表',
  'model': 'YS-801',
  'range': '0.01 s～99 h 59 min 59.99 s；分辨力：0.01 s',
  'manufacturer': '深圳市弈圣科技有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A008',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 9,
  'name': '温湿度计',
  'model': 'YZ-0508',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '扬子',
  'serial_no': '',
  'management_no': 'BPGL-A009',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 10,
  'name': '温湿度计',
  'model': 'YZ-0508',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '扬子',
  'serial_no': '',
  'management_no': 'BPGL-A010',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 11,
  'name': '温湿度计',
  'model': 'YZ-0508',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '扬子',
  'serial_no': '',
  'management_no': 'BPGL-A011',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 12,
  'name': '温湿度计',
  'model': '/',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '蓝骏',
  'serial_no': '/',
  'management_no': 'BPGL-A012',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 13,
  'name': '温湿度计',
  'model': '/',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '蓝骏',
  'serial_no': '/',
  'management_no': 'BPGL-A013',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 14,
  'name': '温湿度计',
  'model': '/',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '蓝骏',
  'serial_no': '/',
  'management_no': 'BPGL-A014',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 15,
  'name': '温湿度计',
  'model': '/',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '蓝骏',
  'serial_no': '/',
  'management_no': 'BPGL-A015',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 16,
  'name': '温湿度计',
  'model': '/',
  'range': '温度：（-10～60）℃；相对湿度：（0～100）%',
  'manufacturer': '蓝骏',
  'serial_no': '/',
  'management_no': 'BPGL-A016',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 17,
  'name': '数显恒温水浴锅',
  'model': 'OW-HF',
  'range': '（5～99.9）℃/0.1 ℃',
  'manufacturer': '浙江欧迈科实验仪器有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A017',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 18,
  'name': '高速精密切割机',
  'model': 'GTQ-5000B',
  'range': '（500～5000）rpm；进刀速度0.01～3 mm/s',
  'manufacturer': '莱州市蔚仪试验器械制造有限公司',
  'serial_no': '02079',
  'management_no': 'BPGL-A018',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 19,
  'name': '金相试样抛光机',
  'model': 'P-2T',
  'range': '/',
  'manufacturer': '莱州市蔚仪试验器械制造有限公司',
  'serial_no': '03127',
  'management_no': 'BPGL-A019',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 20,
  'name': '热膨胀测试仪',
  'model': 'ZRPY-1000',
  'range': '最高温1000 ℃；位移量程：（0～3）mm',
  'manufacturer': '湘潭市湘芸仪器设备有限公司',
  'serial_no': '20251015002',
  'management_no': 'BPGL-A020',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 21,
  'name': '电子万能试验机',
  'model': 'STS50K',
  'range': '（0～50）kN，0.5级；（0～2000）N，0.5级',
  'manufacturer': '厦门易仕特仪器有限公司',
  'serial_no': '20260323020',
  'management_no': 'BPGL-A021',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 22,
  'name': '电子引伸计',
  'model': 'YYJ-5/10-L',
  'range': '（0～5.0）mm，0.5级；标距10.0 mm',
  'manufacturer': '钢研纳克检测技术股份有限公司',
  'serial_no': '260003',
  'management_no': 'BPGL-A022',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 23,
  'name': '挠度计',
  'model': 'B531C',
  'range': '（0～25）mm，0.001 mm',
  'manufacturer': '成都远恒精密测控技术有限公司',
  'serial_no': '3237',
  'management_no': 'BPGL-A023',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 24,
  'name': '耐光色稳定性测试仪',
  'model': 'SGJ611Y',
  'range': '水浴温度（37±1）℃；氙灯辐照度调节范围（2.5～170000）lx；计时范围（0～999999）h',
  'manufacturer': '温州三工匠仪器有限公司',
  'serial_no': '204013',
  'management_no': 'BPGL-A024',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 25,
  'name': '电子天平',
  'model': 'JA503E',
  'range': '（0～500）g；Ⅱ级',
  'manufacturer': '常州市幸运电子设备有限公司',
  'serial_no': '1022605277',
  'management_no': 'BPGL-A025',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 26,
  'name': '影像测量仪',
  'model': 'VMS-2010',
  'range': '',
  'manufacturer': '东莞市辰量仪器设备有限公司',
  'serial_no': 'CL20241028',
  'management_no': 'BPGL-A026',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 27,
  'name': '超声波清洗机',
  'model': 'VGT-1620T',
  'range': '超声频率40 kHz；超声功率50 W',
  'manufacturer': '广东固特超声股份有限公司',
  'serial_no': 'ZZ003635F0002',
  'management_no': 'BPGL-A027',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 28,
  'name': 'D65对色灯箱',
  'model': '',
  'range': '色温：标准6500 K，误差≤±200 K；工业对色最低要求：Ra≥95；箱内工作面照度：500～2000 lux',
  'manufacturer': '工游记工业科技（深圳）有限公司',
  'serial_no': '722773',
  'management_no': 'BPGL-A028',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 29,
  'name': '黑白密度计',
  'model': 'KM-500',
  'range': '0.00～5.00 D',
  'manufacturer': '济宁科锐检测仪器有限公司',
  'serial_no': '124506',
  'management_no': 'BPGL-A029',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 30,
  'name': '电热恒温干燥箱',
  'model': '101-00',
  'range': '加热功率900 W；控温分辨率1 ℃；（50～250）℃；定时范围（1～9999）min',
  'manufacturer': '上海翰雨科技有限公司',
  'serial_no': '951048',
  'management_no': 'BPGL-A030',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 31,
  'name': '微机型酸度计',
  'model': 'PHS-3DW',
  'range': 'pH（0～14），0.01级',
  'manufacturer': '杭州齐威仪器有限公司',
  'serial_no': 'M5260611001',
  'management_no': 'BPGL-A031',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 32,
  'name': '医用X射线限束器',
  'model': 'R103',
  'range': 'X射线泄漏：<0.5 mGy/h（120 kV、4 mA）',
  'manufacturer': '丹东市科大仪器有限公司',
  'serial_no': '',
  'management_no': 'BPGL-A032',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 33,
  'name': '干式激光成像仪',
  'model': 'DryView5700C/6950',
  'range': '/',
  'manufacturer': '锐珂（上海）医疗器材有限公司',
  'serial_no': '69135596',
  'management_no': 'BPGL-A033',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 34,
  'name': '高精度铂电阻温度检测仪',
  'model': 'YET-710',
  'range': '（-40～200）℃',
  'manufacturer': '深圳宇问测量技术有限公司',
  'serial_no': '26056126',
  'management_no': 'BPGL-A034',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 35,
  'name': '数显维氏硬度计',
  'model': 'HV-30Z',
  'range': 'HV10',
  'manufacturer': '上海尚材试验机有限公司',
  'serial_no': '14053',
  'management_no': 'BPGL-A035',
  'purchase_time': '2026.2',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 36,
  'name': '粗糙度仪',
  'model': 'TR200',
  'range': '±160 μm',
  'manufacturer': '掘扬精密量仪有限公司',
  'serial_no': 'SR260117E013',
  'management_no': 'BPGL-A036',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 37,
  'name': '粗糙度标准块',
  'model': '',
  'range': 'Ra 1.61 μm',
  'manufacturer': '掘扬精密量仪有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B001',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 38,
  'name': '研磨粗糙度块',
  'model': '/',
  'range': 'Ra 0.1 μm、Ra 0.05 μm、Ra 0.025 μm',
  'manufacturer': '潍坊华光量具有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-B002',
  'purchase_time': '2026.2',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 39,
  'name': '比色板',
  'model': '3D-MASTER',
  'range': '26色',
  'manufacturer': '德国维他公司',
  'serial_no': 'VT-G360',
  'management_no': 'BPGL-B003',
  'purchase_time': '2026.2',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 40,
  'name': '基托比色板',
  'model': '',
  'range': '',
  'manufacturer': '',
  'serial_no': '',
  'management_no': 'BPGL-B004',
  'purchase_time': '2026.2',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 41,
  'name': '密度片',
  'model': 'DV-9A',
  'range': '0.00～5.00 D',
  'manufacturer': '济宁科锐检测仪器有限公司',
  'serial_no': '265083',
  'management_no': 'BPGL-B005',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 42,
  'name': '背景板',
  'model': '',
  'range': '',
  'manufacturer': '揭阳鸿曦光电有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B006',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 43,
  'name': '标准维氏硬度块',
  'model': '况氏',
  'range': '466HV10',
  'manufacturer': '南昌况氏',
  'serial_no': 'V261-176',
  'management_no': 'BPGL-B007',
  'purchase_time': '2026.2',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 44,
  'name': '三点弯曲试验夹具',
  'model': '',
  'range': '',
  'manufacturer': '厦门易仕特仪器有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B008',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 45,
  'name': '金瓷结合试验夹具',
  'model': '',
  'range': '',
  'manufacturer': '厦门易仕特仪器有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B009',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 46,
  'name': '挠曲弹性试验夹具',
  'model': '',
  'range': '',
  'manufacturer': '厦门易仕特仪器有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B010',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 47,
  'name': '拉力试验夹具',
  'model': '',
  'range': '',
  'manufacturer': '厦门易仕特仪器有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B011',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 48,
  'name': '翘曲变形切割试验夹具',
  'model': '',
  'range': '',
  'manufacturer': '厦门易仕特仪器有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B012',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 49,
  'name': '核辐射检测仪',
  'model': 'SF999',
  'range': 'γ射线、X射线、β射线；剂量当前率：（0.00～1000）μSv/h；灵敏度：80 CPM/μSv（对于Co-60）',
  'manufacturer': '天津瞭望光电科技有限公司',
  'serial_no': '20260121392',
  'management_no': 'BPGL-C001',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 50,
  'name': '放大镜',
  'model': '10X',
  'range': '10X',
  'manufacturer': '惠州市齐力电子',
  'serial_no': '/',
  'management_no': 'BPGL-C002',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 51,
  'name': '放大镜',
  'model': '3X',
  'range': '3X',
  'manufacturer': '惠州市齐力电子',
  'serial_no': '/',
  'management_no': 'BPGL-C003',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 52,
  'name': '牙科探针',
  'model': '',
  'range': '',
  'manufacturer': '',
  'serial_no': '',
  'management_no': 'BPGL-C004',
  'purchase_time': '2026.3',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 53,
  'name': '容量瓶',
  'model': 'A',
  'range': '500 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C005',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 54,
  'name': '容量瓶',
  'model': 'A',
  'range': '1000 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C006',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 55,
  'name': '量筒',
  'model': '/',
  'range': '100 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C007',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 56,
  'name': '量筒',
  'model': '/',
  'range': '1000 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C008',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 57,
  'name': '量筒',
  'model': '/',
  'range': '50 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C009',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 58,
  'name': '量筒',
  'model': '/',
  'range': '25 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C010',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 59,
  'name': '移液管',
  'model': 'A',
  'range': '10 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C011',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 60,
  'name': '通风橱',
  'model': '/',
  'range': '/',
  'manufacturer': '/',
  'serial_no': '/',
  'management_no': 'BPGL-C012',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 61,
  'name': '量筒',
  'model': '/',
  'range': '50 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C013',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 62,
  'name': '量筒',
  'model': '/',
  'range': '25 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C014',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 63,
  'name': '量筒',
  'model': '/',
  'range': '25 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C015',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 64,
  'name': '量筒',
  'model': '/',
  'range': '25 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C016',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 65,
  'name': '量筒',
  'model': '/',
  'range': '100 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C017',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 66,
  'name': '容量瓶',
  'model': 'A',
  'range': '1000 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C018',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 67,
  'name': '容量瓶',
  'model': 'A',
  'range': '500 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C019',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 68,
  'name': '容量瓶',
  'model': 'A',
  'range': '250 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C020',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 69,
  'name': '容量瓶',
  'model': 'A',
  'range': '250 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C021',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 70,
  'name': '容量瓶',
  'model': 'A',
  'range': '250 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C022',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 71,
  'name': '容量瓶',
  'model': 'A',
  'range': '250 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C023',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 72,
  'name': '容量瓶',
  'model': 'A',
  'range': '250 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C024',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 73,
  'name': '容量瓶',
  'model': 'A',
  'range': '100 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C025',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 74,
  'name': '容量瓶',
  'model': 'A',
  'range': '100 mL',
  'manufacturer': 'BOMEX',
  'serial_no': '',
  'management_no': 'BPGL-C026',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 75,
  'name': '移液管',
  'model': 'A',
  'range': '10 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C027',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 76,
  'name': '移液管',
  'model': 'A',
  'range': '1 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C028',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 77,
  'name': '移液管',
  'model': 'A',
  'range': '1 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C029',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 78,
  'name': '移液管',
  'model': 'A',
  'range': '2 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C030',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 79,
  'name': '移液管',
  'model': 'A',
  'range': '2 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C031',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 80,
  'name': '移液管',
  'model': 'A',
  'range': '5 mL',
  'manufacturer': '天玻',
  'serial_no': '',
  'management_no': 'BPGL-C032',
  'purchase_time': '2026.5',
  'calibration_time': '',
  'responsible': '',
  'class': 'C类'},
 {'seq': 81,
  'name': '电子秒表',
  'model': 'YS-860',
  'range': '0.01 s～99 h 59 min 59.99 s；分辨力：0.01 s',
  'manufacturer': '深圳市弈圣科技有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A037',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 82,
  'name': '电子秒表',
  'model': 'YS-860',
  'range': '0.01 s～99 h 59 min 59.99 s；分辨力：0.01 s',
  'manufacturer': '深圳市弈圣科技有限公司',
  'serial_no': '/',
  'management_no': 'BPGL-A038',
  'purchase_time': '2026.4',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 83,
  'name': '照度计',
  'model': '/',
  'range': '（0～200000）Lux；±3%rdg（＜10000 Lux）；±4%rdg（＞10000 Lux）',
  'manufacturer': '得力',
  'serial_no': 'DL333204',
  'management_no': 'BPGL-A039',
  'purchase_time': '',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 84,
  'name': '大理石平台',
  'model': '',
  'range': '（300×200）mm，00级',
  'manufacturer': '山光',
  'serial_no': '',
  'management_no': 'BPGL-A040',
  'purchase_time': '',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 85,
  'name': '高精度数字水平仪',
  'model': 'Dasqua',
  'range': '±0.01 mm/m',
  'manufacturer': '',
  'serial_no': '',
  'management_no': 'BPGL-A041',
  'purchase_time': '',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 86,
  'name': '电子密度天平',
  'model': 'FA2204T·S',
  'range': '（0～220）g，Ⅰ级，0.001 g',
  'manufacturer': '常州市幸运电子设备有限公司',
  'serial_no': '1032606050',
  'management_no': 'BPGL-A042',
  'purchase_time': '',
  'calibration_time': '',
  'responsible': '',
  'class': 'A类'},
 {'seq': 87,
  'name': '标准砝码',
  'model': '200 g',
  'range': '200 g',
  'manufacturer': '常州市幸运电子设备有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B013',
  'purchase_time': '',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'},
 {'seq': 88,
  'name': '标准砝码',
  'model': '200 g',
  'range': '200 g',
  'manufacturer': '常州市幸运电子设备有限公司',
  'serial_no': '',
  'management_no': 'BPGL-B014',
  'purchase_time': '',
  'calibration_time': '',
  'responsible': '',
  'class': 'B类'}]

EXPERIMENT_DEFAULT_LOCATIONS = {'表面粗糙度试验': '性能检测室',
 '金属-陶瓷结合裂纹萌生试验': '性能检测室',
 '金属内部质量X射线灰度分析': '无损检测室',
 '翘曲变形试验': '显微检测室',
 '热膨胀系数试验': '性能检测室',
 '陶瓷牙耐急冷急热试验': '性能检测室',
 '弯曲性能试验': '性能检测室',
 '维氏硬度试验': '性能检测室',
 '增材制造金属试样厚度测量': '显微检测室',
 '牙科材料色稳定性试验': '外观检测室'}

EXPERIMENT_EQUIPMENT_BINDINGS = {'表面粗糙度试验': [{'management_no': 'BPGL-A036', 'role': '主设备', 'required': True, 'note': '触针式粗糙度测量'},
             {'management_no': 'BPGL-B001', 'role': '标准器', 'required': True, 'note': '使用前标准块核查'},
             {'management_no': 'BPGL-B002', 'role': '标准器', 'required': False, 'note': '低粗糙度参考/核查'},
             {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': False, 'note': '试样尺寸和定位确认'},
             {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '必要时清洁试样'},
             {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A040', 'role': '测量平台', 'required': True, 'note': '00级大理石平台，用于粗糙度仪及小试样稳定放置'},
             {'management_no': 'BPGL-A041', 'role': '水平确认', 'required': True, 'note': '确认平台及测量方向水平状态'}],
 '金属-陶瓷结合裂纹萌生试验': [{'management_no': 'BPGL-A021', 'role': '主设备', 'required': True, 'note': '加载与力值采集'},
                   {'management_no': 'BPGL-B009', 'role': '夹具', 'required': True, 'note': '金属-陶瓷结合试验专用夹具'},
                   {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': True, 'note': '跨距、宽度等尺寸测量'},
                   {'management_no': 'BPGL-A002', 'role': '辅助量具', 'required': True, 'note': '金属基体厚度测量'},
                   {'management_no': 'BPGL-A018', 'role': '制样设备', 'required': False, 'note': '试样切割制备'},
                   {'management_no': 'BPGL-A019', 'role': '制样设备', 'required': False, 'note': '试样表面处理'},
                   {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '试样清洁'},
                   {'management_no': 'BPGL-C002', 'role': '外观检查', 'required': True, 'note': '10倍观察裂纹/剥离形态'},
                   {'management_no': 'BPGL-C003', 'role': '外观检查', 'required': False, 'note': '辅助观察'},
                   {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'}],
 '金属内部质量X射线灰度分析': [{'management_no': 'BPGL-A032', 'role': '主设备', 'required': True, 'note': 'X射线限束与曝光'},
                   {'management_no': 'BPGL-A033', 'role': '成像设备', 'required': True, 'note': '影像输出'},
                   {'management_no': 'BPGL-A029', 'role': '测量设备', 'required': True, 'note': '黑白密度测量'},
                   {'management_no': 'BPGL-B005', 'role': '标准器', 'required': True, 'note': '密度计核查'},
                   {'management_no': 'BPGL-C001', 'role': '安全监测', 'required': True, 'note': '辐射安全监测'},
                   {'management_no': 'BPGL-B006', 'role': '辅助器具', 'required': False, 'note': '统一成像/观察背景'},
                   {'management_no': 'BPGL-A005', 'role': '辅助量具', 'required': False, 'note': '厚度复核'},
                   {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': False, 'note': '尺寸与摆位确认'},
                   {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '样品清洁'},
                   {'management_no': 'BPGL-C002', 'role': '外观检查', 'required': False, 'note': '影像/样品辅助观察'},
                   {'management_no': 'BPGL-C003', 'role': '外观检查', 'required': False, 'note': '影像/样品辅助观察'},
                   {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                   {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'}],
 '翘曲变形试验': [{'management_no': 'BPGL-A026', 'role': '主设备', 'required': True, 'note': 'H1、H2影像测量'},
            {'management_no': 'BPGL-A018', 'role': '制样设备', 'required': True, 'note': '切割悬臂试样'},
            {'management_no': 'BPGL-B012', 'role': '夹具', 'required': True, 'note': '翘曲变形切割定位'},
            {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': False, 'note': '试样尺寸确认'},
            {'management_no': 'BPGL-A002', 'role': '辅助量具', 'required': False, 'note': '厚度复核'},
            {'management_no': 'BPGL-A003', 'role': '辅助量具', 'required': False, 'note': '位移/平面状态辅助核查'},
            {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '切割后清洁'},
            {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'}],
 '热膨胀系数试验': [{'management_no': 'BPGL-A020', 'role': '主设备', 'required': True, 'note': '热膨胀曲线与系数测量'},
             {'management_no': 'BPGL-A034', 'role': '温度测量', 'required': True, 'note': '温度系统核查'},
             {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': True, 'note': '试样长度测量'},
             {'management_no': 'BPGL-A002', 'role': '辅助量具', 'required': False, 'note': '试样尺寸复核'},
             {'management_no': 'BPGL-A004', 'role': '备用量具', 'required': False, 'note': '特殊形状尺寸备用测量'},
             {'management_no': 'BPGL-A030', 'role': '制样设备', 'required': False, 'note': '试样干燥'},
             {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '试样清洁'},
             {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
             {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'}],
 '陶瓷牙耐急冷急热试验': [{'management_no': 'BPGL-A030', 'role': '主设备', 'required': True, 'note': '100±2℃加热'},
                {'management_no': 'BPGL-A034', 'role': '温度测量', 'required': True, 'note': '烘箱、冰水和冷却温度确认'},
                {'management_no': 'BPGL-A006', 'role': '计时设备', 'required': True, 'note': '加热、转移和浸泡计时'},
                {'management_no': 'BPGL-A007', 'role': '计时设备', 'required': False, 'note': '备用计时'},
                {'management_no': 'BPGL-A008', 'role': '计时设备', 'required': False, 'note': '备用计时'},
                {'management_no': 'BPGL-C002', 'role': '外观检查', 'required': True, 'note': '10倍检查裂纹、崩瓷和破裂'},
                {'management_no': 'BPGL-A028', 'role': '光照设备', 'required': True, 'note': '检查区域光照'},
                {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '样品清洗'},
                {'management_no': 'BPGL-A017', 'role': '恒温设备', 'required': False, 'note': '温度介质预调/备用'},
                {'management_no': 'BPGL-C004', 'role': '辅助检查', 'required': False, 'note': '缺陷辅助确认'},
                {'management_no': 'BPGL-A025', 'role': '称量设备', 'required': False, 'note': '清洗液配制'},
                {'management_no': 'BPGL-C006', 'role': '溶液配制', 'required': False, 'note': '冰水/清洗液配制'},
                {'management_no': 'BPGL-C008', 'role': '溶液配制', 'required': False, 'note': '冰水/清洗液量取'},
                {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A037', 'role': '计时设备', 'required': True, 'note': '新版YS-860秒表，用于加热、转移和浸泡计时'},
                {'management_no': 'BPGL-A038', 'role': '计时设备', 'required': False, 'note': '新版YS-860备用计时'},
                {'management_no': 'BPGL-A039', 'role': '光照确认', 'required': False, 'note': '检查区域照度确认'}],
 '弯曲性能试验': [{'management_no': 'BPGL-A021', 'role': '主设备', 'required': True, 'note': '加载与力值采集'},
            {'management_no': 'BPGL-A023', 'role': '位移测量', 'required': True, 'note': '挠度测量'},
            {'management_no': 'BPGL-B008', 'role': '夹具', 'required': True, 'note': '三点弯曲加载'},
            {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': True, 'note': '试样尺寸和跨距测量'},
            {'management_no': 'BPGL-A002', 'role': '辅助量具', 'required': True, 'note': '宽度和厚度测量'},
            {'management_no': 'BPGL-A022', 'role': '位移测量', 'required': False, 'note': '电子引伸计备用/比对'},
            {'management_no': 'BPGL-B010', 'role': '夹具', 'required': False, 'note': '挠曲弹性项目备用'},
            {'management_no': 'BPGL-B011', 'role': '备用夹具', 'required': False, 'note': '当前方法不默认使用，方法扩展经批准后启用'},
            {'management_no': 'BPGL-A017', 'role': '恒温设备', 'required': False, 'note': '需要水浴条件时使用'},
            {'management_no': 'BPGL-A003', 'role': '辅助量具', 'required': False, 'note': '夹具平行/位移辅助核查'},
            {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A040', 'role': '测量平台', 'required': False, 'note': '夹具校准及量具辅助基准'},
            {'management_no': 'BPGL-A041', 'role': '水平确认', 'required': False, 'note': '三点弯曲夹具水平状态确认'}],
 '维氏硬度试验': [{'management_no': 'BPGL-A035', 'role': '主设备', 'required': True, 'note': 'HV10试验'},
            {'management_no': 'BPGL-B007', 'role': '标准器', 'required': True, 'note': '标准硬度块核查'},
            {'management_no': 'BPGL-A036', 'role': '表面确认', 'required': False, 'note': '测试面粗糙度实测'},
            {'management_no': 'BPGL-B002', 'role': '标准器', 'required': False, 'note': '粗糙度核查参考'},
            {'management_no': 'BPGL-A018', 'role': '制样设备', 'required': False, 'note': '试样切割'},
            {'management_no': 'BPGL-A019', 'role': '制样设备', 'required': False, 'note': '测试面磨抛'},
            {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '测试面清洁'},
            {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': False, 'note': '试样尺寸确认'},
            {'management_no': 'BPGL-A002', 'role': '辅助量具', 'required': False, 'note': '试样厚度确认'},
            {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
            {'management_no': 'BPGL-A040', 'role': '测量平台', 'required': False, 'note': '硬度计/试样辅助稳定与水平基准'},
            {'management_no': 'BPGL-A041', 'role': '水平确认', 'required': False, 'note': '设备与试样台水平状态核查'}],
 '增材制造金属试样厚度测量': [{'management_no': 'BPGL-A026', 'role': '主设备', 'required': True, 'note': '二次元影像法厚度测量'},
                  {'management_no': 'BPGL-A001', 'role': '辅助量具', 'required': False, 'note': '尺寸复核'},
                  {'management_no': 'BPGL-A002', 'role': '辅助量具', 'required': False, 'note': '厚度比对'},
                  {'management_no': 'BPGL-A005', 'role': '辅助量具', 'required': False, 'note': '厚度比对'},
                  {'management_no': 'BPGL-A004', 'role': '备用量具', 'required': False, 'note': '特殊部位厚度备用测量'},
                  {'management_no': 'BPGL-A018', 'role': '制样设备', 'required': False, 'note': '必要时切割制样'},
                  {'management_no': 'BPGL-A027', 'role': '清洗设备', 'required': False, 'note': '测量前清洁'},
                  {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                  {'management_no': 'BPGL-A040', 'role': '测量平台', 'required': False, 'note': '影像测量及量具辅助稳定基准'},
                  {'management_no': 'BPGL-A041', 'role': '水平确认', 'required': False, 'note': '测量平台水平状态确认'}],
 '牙科材料色稳定性试验': [{'management_no': 'BPGL-A024', 'role': '主设备', 'required': True, 'note': '耐光色稳定性试验'},
                {'management_no': 'BPGL-A028', 'role': '光照设备', 'required': True, 'note': 'D65标准光源对色'},
                {'management_no': 'BPGL-B003', 'role': '标准器', 'required': True, 'note': '牙色比色参考'},
                {'management_no': 'BPGL-B004', 'role': '标准器', 'required': False, 'note': '基托材料比色参考'},
                {'management_no': 'BPGL-B006', 'role': '辅助器具', 'required': True, 'note': '统一观察背景'},
                {'management_no': 'BPGL-A031', 'role': '测量设备', 'required': True, 'note': '试验溶液pH确认'},
                {'management_no': 'BPGL-A025', 'role': '称量设备', 'required': True, 'note': '试剂/溶液配制'},
                {'management_no': 'BPGL-A034', 'role': '温度测量', 'required': True, 'note': '水浴温度核查'},
                {'management_no': 'BPGL-A006', 'role': '计时设备', 'required': False, 'note': '暴露/处理时间核查'},
                {'management_no': 'BPGL-A007', 'role': '计时设备', 'required': False, 'note': '备用计时'},
                {'management_no': 'BPGL-A008', 'role': '计时设备', 'required': False, 'note': '备用计时'},
                {'management_no': 'BPGL-A017', 'role': '恒温设备', 'required': False, 'note': '试样条件化/备用水浴'},
                {'management_no': 'BPGL-A030', 'role': '干燥设备', 'required': False, 'note': '试样干燥'},
                {'management_no': 'BPGL-C003', 'role': '外观检查', 'required': False, 'note': '辅助观察'},
                {'management_no': 'BPGL-C005', 'role': '溶液配制', 'required': True, 'note': '500 mL容量配制'},
                {'management_no': 'BPGL-C006', 'role': '溶液配制', 'required': True, 'note': '1000 mL容量配制'},
                {'management_no': 'BPGL-C007', 'role': '溶液配制', 'required': True, 'note': '100 mL量取'},
                {'management_no': 'BPGL-C008', 'role': '溶液配制', 'required': True, 'note': '1000 mL量取'},
                {'management_no': 'BPGL-C012', 'role': '安全设施', 'required': True, 'note': '溶液配制和操作防护'},
                {'management_no': 'BPGL-A009', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A010', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A011', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A012', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A013', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A014', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A015', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A016', 'role': '环境监测', 'required': False, 'note': '记录温度和相对湿度'},
                {'management_no': 'BPGL-A037', 'role': '计时设备', 'required': False, 'note': '暴露和处理时间核查'},
                {'management_no': 'BPGL-A038', 'role': '计时设备', 'required': False, 'note': '备用计时'},
                {'management_no': 'BPGL-A039', 'role': '光照确认', 'required': True, 'note': 'D65对色灯箱及观察区域照度确认'},
                {'management_no': 'BPGL-A042', 'role': '称量/密度设备', 'required': False, 'note': '样品或试液质量、密度辅助确认'},
                {'management_no': 'BPGL-B013', 'role': '标准器', 'required': False, 'note': '电子密度天平200 g标准砝码核查'},
                {'management_no': 'BPGL-B014', 'role': '标准器', 'required': False, 'note': '电子密度天平200 g备用标准砝码核查'},
                {'management_no': 'BPGL-C009', 'role': '量取器具', 'required': False, 'note': '50 mL量筒，试液量取'},
                {'management_no': 'BPGL-C010', 'role': '量取器具', 'required': False, 'note': '25 mL量筒，试液量取'},
                {'management_no': 'BPGL-C011', 'role': '移液器具', 'required': False, 'note': '10 mL移液管，试液移取'},
                {'management_no': 'BPGL-C013', 'role': '量取器具', 'required': False, 'note': '50 mL量筒，备用试液量取'},
                {'management_no': 'BPGL-C014', 'role': '量取器具', 'required': False, 'note': '25 mL量筒，备用试液量取'},
                {'management_no': 'BPGL-C015', 'role': '量取器具', 'required': False, 'note': '25 mL量筒，备用试液量取'},
                {'management_no': 'BPGL-C016', 'role': '量取器具', 'required': False, 'note': '25 mL量筒，备用试液量取'},
                {'management_no': 'BPGL-C017', 'role': '量取器具', 'required': False, 'note': '100 mL量筒，备用试液量取'},
                {'management_no': 'BPGL-C018', 'role': '容量器具', 'required': False, 'note': '1000 mL容量瓶，备用溶液配制'},
                {'management_no': 'BPGL-C019', 'role': '容量器具', 'required': False, 'note': '500 mL容量瓶，备用溶液配制'},
                {'management_no': 'BPGL-C020', 'role': '容量器具', 'required': False, 'note': '250 mL容量瓶，溶液配制'},
                {'management_no': 'BPGL-C021', 'role': '容量器具', 'required': False, 'note': '250 mL容量瓶，溶液配制'},
                {'management_no': 'BPGL-C022', 'role': '容量器具', 'required': False, 'note': '250 mL容量瓶，溶液配制'},
                {'management_no': 'BPGL-C023', 'role': '容量器具', 'required': False, 'note': '250 mL容量瓶，溶液配制'},
                {'management_no': 'BPGL-C024', 'role': '容量器具', 'required': False, 'note': '250 mL容量瓶，备用溶液配制'},
                {'management_no': 'BPGL-C025', 'role': '容量器具', 'required': False, 'note': '100 mL容量瓶，溶液配制'},
                {'management_no': 'BPGL-C026', 'role': '容量器具', 'required': False, 'note': '100 mL容量瓶，备用溶液配制'},
                {'management_no': 'BPGL-C027', 'role': '移液器具', 'required': False, 'note': '10 mL移液管，备用试液移取'},
                {'management_no': 'BPGL-C028', 'role': '移液器具', 'required': False, 'note': '1 mL移液管，试液移取'},
                {'management_no': 'BPGL-C029', 'role': '移液器具', 'required': False, 'note': '1 mL移液管，备用试液移取'},
                {'management_no': 'BPGL-C030', 'role': '移液器具', 'required': False, 'note': '2 mL移液管，试液移取'},
                {'management_no': 'BPGL-C031', 'role': '移液器具', 'required': False, 'note': '2 mL移液管，备用试液移取'},
                {'management_no': 'BPGL-C032', 'role': '移液器具', 'required': False, 'note': '5 mL移液管，试液移取'}]}

EQUIPMENT_BINDING_ROLES = ['主设备',
 '成像设备',
 '测量设备',
 '位移测量',
 '温度测量',
 '辅助量具',
 '备用量具',
 '表面确认',
 '标准器',
 '夹具',
 '备用夹具',
 '制样设备',
 '清洗设备',
 '环境监测',
 '安全监测',
 '安全设施',
 '计时设备',
 '恒温设备',
 '干燥设备',
 '称量设备',
 '光照设备',
 '外观检查',
 '辅助检查',
 '辅助器具',
 '溶液配制',
 '测量平台',
 '水平确认',
 '光照确认',
 '称量/密度设备',
 '量取器具',
 '容量器具',
 '移液器具']
